import os

print("GOOGLE_APPLICATION_CREDENTIALS =", os.getenv("GOOGLE_APPLICATION_CREDENTIALS"))
print("GOOGLE_GENAI_USE_VERTEXAI =", os.getenv("GOOGLE_GENAI_USE_VERTEXAI"))
print("GOOGLE_CLOUD_PROJECT =", os.getenv("GOOGLE_CLOUD_PROJECT"))